### ISSUE TITLE
Inversion Code/Instructions

### ISSUE THREAD

**Issue by ChikaYan** [oneThousand1000/LPFF-dataset#3]
Hi,

Thank you for the brilliant work! 

May I ask if it's possible to release the GAN inversion code/instruction that is used to evaluate image inversion performance in the paper (figure9)? Or, was the codebase of https://github.com/jiaxinxie97/HFGI3D used directly without modification?

Many thanks

**Comment by oneThousand1000** [comment]
Hello! We directly used the codebase from https://github.com/jiaxinxie97/HFGI3D, since we did not modify the main architecture of eg3d. However, please be aware that we corrected the tri-plane bug present in the original eg3d (see https://github.com/NVlabs/eg3d/issues/67). So make sure that the model you use in HFGI3D also has the updated tri-plane.

At this time, we have no plans to release the inversion code, as we made some minor but cosmetic changes (e.g. to the data path). If you face any issues reproducing our results, we are happy to share our code with you.

**Comment by ChikaYan** [comment]
Thx a lot for the quick response!
